---
- hosts: all
  become: yes
  tasks:
         - name: updating vm
           shell: apt update
         - name: installing java
           apt:
                name: openjdk-8-jre-headless
                state: present
                install_recommends: no
         - name: installing apache
           get_url: url=https://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.50/bin/apache-tomcat-8.5.50.tar.gz dest=/home/ubuntu/
         - name: Extracting tar file
           unarchive: src=/home/ubuntu/apache-tomcat-8.5.50.tar.gz dest=/home/ubuntu/ remote_src=yes
         - name: copying the war file
           copy: 
             src: target/insurence.war
             dest: /home/ubuntu/apache-tomcat-8.5.50/webapps/
        # - name: downloading war file
       #    get_url: url=https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war dest=/home/ubuntu/apache-tomcat-8.5.50/webapps/
         - name: starting server
           command: nohup "/home/ubuntu/apache-tomcat-8.5.50/bin/startup.sh"
